### ISSUE TITLE
Mason checkhealth incorrectly reporting Julia missing

### ISSUE THREAD

**Issue by ReallySnazzy** [williamboman/mason.nvim#1157]
### I've searched open issues for similar requests

Yes

### I've manually reviewed logs to find potential errors

Yes

### I've recently downloaded the latest plugin version of mason.nvim

- [X] Yes

### Problem description

1.)
When I run `:checkhealth mason` on Windows using LunarVim. I get the issue `WARNING: julia: not available`. 
```
julia --version
julia version 1.9.0-rc1
```
I'm also able to verify that I have LanguageServer.jl.

Running :MasonInstall julia-lsp gives back
```
  Failed
    ◍ julia-lsp
      julia was not found in path.
      See https://julialang.org/downloads/ for installation instructions.
      ...acker\start\mason.nvim/lua\mason-core\installer\init.lua:121: Installation failed: system executable was not found.
 ```

I installed julia using juliaup. Julia was previously showing in :checkhealth mason, but after upgrading that is no longer the case. Additionally I didn't install using juliaup last time. In my previous setup the julia lsp wasn't working either which is what prompted me upgrading.

2.)
I was trying to debug this issue from the locally installed mason files in my neovim installation. One interesting thing I noticed is 
`:lua print(vim.fn.executable("julia"))` and `:lua print(vim.fn.executable("julia.exe"))` both give back 0. However, `:!julia --version` correctly prints the locally installed julia version. I think something other than vim.fn.executable should be used since that doesn't seem reliable for determining if something is on the path.

### Expected behavior

I should be able to install and use the Julia language server.

### Steps to reproduce

1. Install juliaup from Windows Store
2. Install julia using `juliaup add 1.9.0`
3. Install lunarvim
4. Confirm julia is on path either by finding the folder in the path environment variable or running `julia --version` from powershell
5. Run `:checkhealth mason`. If it provides an error about julia not being available then you have reproduced the bug.

### Affected packages

All

### Neovim version (>= 0.7)

NVIM v0.8.3
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compiled by runneradmin@fv-az171-224

Features: -acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info

### Operating system/version

OS Name	Microsoft Windows 11 Home Version	10.0.22621 Build 22621

### Healthcheck

```Text
mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: **Go**: `go version go1.18.1 windows/amd64`
  - OK: **cargo**: `cargo 1.68.0-nightly (70898e522 2022-12-05)`
  - OK: **luarocks**: `luarocks 3.9.0
`
  - OK: **Ruby**: `ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x64-mingw32]
`
  - OK: **RubyGem**: `3.2.22
`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `8.5.5`
  - OK: **node**: `v16.15.0
`
  - OK: **python3**: `Python 3.10.5
`
  - OK: **pip3**: `pip 22.0.4 from D:\Python310\lib\site-packages\pip (python 3.10)

`
  - OK: **javac**: `Ok`
  - OK: **java**: `openjdk version "1.8.0_345"
`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on mingw32.
`
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - OK: **gzip**: `gzip 1.3.12
`
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp bz2lib/1.0.6 
`
  - OK: **python**: `Python 3.10.5
`
  - OK: **pip**: `pip 22.0.4 from D:\Python310\lib\site-packages\pip (python 3.10)

`
  - OK: **7z**: `7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
`
  - OK: **JAVA_HOME**: `openjdk version "1.8.0_345"
`
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: 3/31/2023 12:54:44 AM.
```

**Comment by ReallySnazzy** [comment]
Seems to also be an issue for Neovim newest release
NVIM v0.9.0-dev-1296+g8b7fb668e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

**Comment by ReallySnazzy** [comment]
Looks like the windows store version only has this issue. I think I remember windows store doing some strange sandboxing thing, so perhaps despite having an absolute path some applications cannot see the file. After installing the msi version from julia's website directly, this issue resolves itself.

**Comment by ReallySnazzy** [comment]
This second issue was resolved by updating environment to match steps mentioned in julia docs
https://github.com/williamboman/mason-lspconfig.nvim/blob/main/lua/mason-lspconfig/server_configurations/julials/README.md

**Comment by olejorik** [comment]
I have juila installed via `juliaup` and I've resolved the first issue by adding `C:\Users\olegs\.julia\juliaup\julia-1.11.4+0.x64.w64.mingw32\bin` to my system path (make sure it's on top of the list).

LSP is still not working (yet), although the steps from the docs are completed.

```
mason:                                         require("mason.health").check()

mason.nvim ~
- OK mason.nvim version v1.11.0
- OK PATH: prepend
- OK Providers: 
    mason.providers.registry-api
    mason.providers.client
- OK neovim version >= 0.7.0

mason.nvim [Registries] ~
- OK Registry `github.com/mason-org/mason-registry version: 2025-03-20-daring-idol` is installed.

mason.nvim [Core utils] ~
- WARNING unzip: not available
  - ADVICE:
    - spawn: unzip failed with exit code - and signal -. unzip is not executable
- WARNING wget: not available
  - ADVICE:
    - spawn: wget failed with exit code - and signal -. wget is not executable
- OK curl: `curl 8.10.1 (Windows) libcurl/8.10.1 Schannel zlib/1.3 WinIDN
`
- WARNING gzip: not available
  - ADVICE:
    - spawn: gzip failed with exit code - and signal -. gzip is not executable
- OK tar: `bsdtar 3.7.7 - libarchive 3.7.7 zlib/1.2.13.1-motley liblzma/5.4.3 bz2lib/1.0.8 libzstd/1.5.5 
`
- OK pwsh: `7.4.7 Microsoft Windows 10.0.26100 Win32NT
`
- WARNING 7z: not available
  - ADVICE:
    - spawn: 7z failed with exit code - and signal -. 7z is not executable

mason.nvim [Languages] ~
- WARNING Go: not available
  - ADVICE:
    - spawn: go failed with exit code - and signal -. go is not executable
- WARNING cargo: not available
  - ADVICE:
    - spawn: cargo failed with exit code - and signal -. cargo is not executable
- WARNING luarocks: not available
  - ADVICE:
    - spawn: luarocks failed with exit code - and signal -. luarocks is not executable
- WARNING Ruby: not available
  - ADVICE:
    - spawn: ruby failed with exit code - and signal -. ruby is not executable
- WARNING RubyGem: not available
  - ADVICE:
    - spawn: gem.cmd failed with exit code - and signal -. gem.cmd is not executable
- WARNING Composer: not available
  - ADVICE:
    - spawn: composer.bat failed with exit code - and signal -. composer.bat is not executable
- WARNING PHP: not available
  - ADVICE:
    - spawn: php failed with exit code - and signal -. php is not executable
- WARNING npm: not available
  - ADVICE:
    - spawn: npm.cmd failed with exit code - and signal -. npm.cmd is not executable
- WARNING node: not available
  - ADVICE:
    - spawn: node failed with exit code - and signal -. node is not executable
- WARNING javac: not available
  - ADVICE:
    - spawn: javac failed with exit code - and signal -. javac is not executable
- OK python: `Python 3.12.4
`
- OK julia: `julia version 1.11.4`
- OK java: `java version "1.8.0_431"
`
- OK pip: `pip 24.0 from C:\Users\olegs\miniconda3\Lib\site-packages\pip (python 3.12)

`
- OK python venv: `Ok`

mason.nvim [GitHub] ~
- OK GitHub API rate limit. Used: 0. Remaining: 60. Limit: 60. Reset: 20-3-2025 21:49:54.
  Install and authenticate via gh-cli to increase rate limit.

```
